### ISSUE TITLE
Duplicated titles

### ISSUE THREAD

**Issue by MissPhilbin** [raspberrypilearning/teachers-guide#3]
@MarcScott Two of the steps in physical-setup.md have the same title. Is this intentional?

**Comment by MarcScott** [comment]
Are you referring to:
_Use a KVM switch_ and _Use a KVM device_?
If so, then yes this is intentional.

**Comment by MissPhilbin** [comment]
Can we change them up a bit? The audience is newbies and 'KVM device' sounds too jargon-like and too easily confused with 'use a KVM switch'.
