### ISSUE TITLE
Update remote.md and vnc-*.md for Jessie PIXEL

### ISSUE THREAD

**Issue by lurch** [raspberrypilearning/teachers-guide#4]
...as hinted at by https://github.com/raspberrypi/documentation/issues/340

Now that Raspbian includes RealVNC built-in, does https://www.raspberrypi.org/learning/teachers-guide/remote/ need to be updated to suit? c.f. https://github.com/raspberrypi/documentation/pull/432

**Comment by MarcScott** [comment]
Now fixed on update branch. Will be published after copy edit. Cheers

**Comment by lurch** [comment]
@minkustree Does https://github.com/raspberrypi/documentation/pull/508 mean that the update branch in this repo that @MarcScott refers to will need updating again?

**Comment by minkustree** [comment]
@lurch The instructions in the update branch are still valid with the new version of VNC, so no pressing need for any changes (other than perhaps to update the screenshots to the new icon colour!)
